apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: vnys-smailandstuff
spec:
  # build:
    # secrets:
      # - SNYK_TOKEN
  environments:
    - name: production
      build:
        from: master
  components:
    - name: webapp
      src: .
      ports:
       - name: http
         port: 3000
      public: true
      replicas: 1
      environmentConfig:
        - environment: production
          variables:
            TENANTID: "3aa4a235-b6e2-48d5-9195-7fcf05b459b0"
            CLIENTID: "5decb298-e7a2-4b9c-8628-bd411c71d6a9"
            NODE_ENV: "development"
      secrets:
        - CLIENTSECRET
